defmodule Tidetracker.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:team, primary_key: false) do
      add :home_pool_id,
          references(:pool, column: :id, name: "team_home_pool_id_fkey", type: :bigint)

      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:pool, primary_key: false) do
      add :short_name, :text, null: false
      add :name, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end

    create table(:meet_team, primary_key: false) do
      add :team_id, references(:team, column: :id, name: "meet_team_team_id_fkey", type: :bigint),
        primary_key: true,
        null: false

      add :meet_id, references(:meet, column: :id, name: "meet_team_meet_id_fkey", type: :bigint),
        primary_key: true,
        null: false
    end

    create table(:meet, primary_key: false) do
      add :date, :date, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:meet)

    drop constraint(:meet_team, "meet_team_meet_id_fkey")

    drop constraint(:meet_team, "meet_team_team_id_fkey")

    drop table(:meet_team)

    drop table(:pool)

    drop constraint(:team, "team_home_pool_id_fkey")

    drop table(:team)
  end
end