defmodule Tidetracker.Repo.Migrations.MeetNameAndLocation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:meet) do
      add :name, :text

      add :location_id,
          references(:pool, column: :id, name: "meet_location_id_fkey", type: :bigint)
    end
  end

  def down do
    alter table(:meet) do
      remove :location_id
      remove :name
    end
  end
end
